### ISSUE TITLE
Dataset about  TrafficLightRecognition

### ISSUE THREAD

**Issue by cuicui1** [stephendj/TrafficLightRecognition#1]
Hello，I want the dataset about this project,thank you very much.

**Comment by stephendj** [comment]
@cuicui1 Hi there, actually I got the dataset from here http://cvrr.ucsd.edu/vivachallenge/index.php/traffic-light/traffic-light-detection/, you are free to use it as long as you give a proper acknowledgement (it's described there in the link).

**Comment by cuicui1** [comment]
Thank you very much!If you can provide me a trained model.xml, I would be approciate very much.

**Comment by cuicui1** [comment]
Hello，what is the nightTrainInstances in your code？

**Comment by stephendj** [comment]
@cuicui1 the trained model is quite big, i'm sure you can generate it by running the code. I divided my training data into 2 types, morning and night, so that nightTrainInstances should be train instances for night data.

**Comment by cuicui1** [comment]
Thank you very much，this is my email address X.T.Cui@hotmail.com, can you send me the full project to my address including nightTrainInstances、nightTrainLabels、nightTestInstances、nightTestLabels and trained model.
